//-----------------------------------------------------------------------------
// Copyright 2022, Ed Keenan, all rights reserved.
//----------------------------------------------------------------------------- 


#include "Quat_AddSubMultDiv.cpp"                               
#include "Quat_Boolean.cpp"                                     
#include "Quat_ConstantMinusQuat.cpp"                           
#include "Quat_ConstantMinusQuatMinusConstant.cpp"              
#include "Quat_ConstantPlusQuat.cpp"                            
#include "Quat_ConstantPlusQuatPlusConstant.cpp"                
#include "Quat_ConstDivQuat.cpp"                                
#include "Quat_Constructor.cpp"                                 
#include "Quat_ConstTimesQuat.cpp"                              
#include "Quat_EqualOperator.cpp"                               
#include "Quat_Functions.cpp"                                   
#include "Quat_Get_Accessors.cpp"                               
#include "Quat_Get_Accessors_const.cpp"                                                              
#include "Quat_IsConjugateEqual.cpp"                            
#include "Quat_IsConjugateEqual2.cpp"                           
#include "Quat_IsEqual.cpp"                                     
#include "Quat_IsEqual1.cpp"                                    
#include "Quat_IsEquivalent.cpp"                                
#include "Quat_IsEquivalent2.cpp"                               
#include "Quat_IsEquivalent3.cpp"                               
#include "Quat_IsIdentity.cpp"                                  
#include "Quat_IsIdentity2.cpp"                                 
#include "Quat_IsNegEqual.cpp"                                  
#include "Quat_IsNegEqual2.cpp"                                 
#include "Quat_IsNormalized.cpp"                                
#include "Quat_IsNormalized2.cpp"                               
#include "Quat_IsZero.cpp"                                      
#include "Quat_IsZero2.cpp"                                     
#include "Quat_MatrixTimesQuat.cpp"                             
#include "Quat_MinusOperator.cpp"                               
#include "Quat_PlusOperator.cpp"                                
#include "Quat_Proxy.cpp"                                       
#include "Quat_QuatDivConst.cpp"                                
#include "Quat_QuatDivEqualConst.cpp"                           
#include "Quat_QuatDivEqualQuat.cpp"                            
#include "Quat_QuatDivQuat.cpp"                                 
#include "Quat_QuatMinusConstant.cpp"                           
#include "Quat_QuatMinusConstantMinusQuat.cpp"                  
#include "Quat_QuatMinusEqualConst.cpp"                         
#include "Quat_QuatMinusEqualQuat.cpp"                          
#include "Quat_QuatMinusQuat.cpp"                               
#include "Quat_QuatPlusConstant.cpp"                            
#include "Quat_QuatPlusConstPlusQuat.cpp"                       
#include "Quat_QuatPlusEqualConstant.cpp"                       
#include "Quat_QuatPlusEqualQuat.cpp"                           
#include "Quat_QuatPlusQuat.cpp"                                
#include "Quat_QuatTimeConst.cpp"                               
#include "Quat_QuatTimeEqualQuat.cpp"                           
#include "Quat_QuatTimesEqualConst.cpp"                         
#include "Quat_QuatTimesEqualMatrix.cpp"                        
#include "Quat_QuatTimesMatrix.cpp"                             
#include "Quat_QuatTimesQuat.cpp"                               
#include "Quat_SetGet.cpp"                                      
#include "Quat_Set_Accessors.cpp"                               
#include "Quat_Set_Accessors_get.cpp"                           
#include "Quat_vectTimesEqualQuat.cpp"                          
#include "Quat_vectTimesEqualQuat2.cpp"                         
#include "Quat_vectTimesQuat.cpp"                               
#include "Quat_vectTimesQuat2.cpp"                              



// ---  End of File ---
